all:
  hosts:
    local:
      ansible_host: 127.0.0.1
      project: local
      ansible_user: root
#  pre_tasks:
#    - name: Update Apt
#      become: true
#      apt:
#        update_cache: yes
#        state: present
