- name: Update repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apts }}"

- name: Install a .deb package
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
  with_items: "{{ debs }}"

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes
    purge: true
