- name: Update repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apts }}"

- name: Install deb packages
  become: true
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
  with_items: "{{ debs }}"

- name: Download and extract binary file
  become: true
  ansible.builtin.unarchive:
    src: "{{ item.url }}"
    dest: "/usr/sbin/"
    remote_src: yes
    extra_opts:
      - '--strip-components=1'
    creates: "/usr/sbin/{{ item.name }}"
  loop: "{{ bins_archive }}"

- name: Ensure binary is executable and accessible
  become: true
  ansible.builtin.file:
    path: "/usr/sbin/{{ item.name }}"
    mode: '0755'
    owner: root
    group: root
  loop: "{{ bins_archive }}"

- name: Clean
  become: true
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
