- name: Update repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apts }}"

- name: Install deb packages
  become: true
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
  with_items: "{{ debs }}"

- name: Clean
  become: true
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
    purge: true
