- name: Install and enable GNOME extensions
  shell: roles/install-gnome-extensions/install-gnome-extensions.sh --enable {{ item.id }}
  loop: "{{ gnome_extensions }}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ gnome_extension_dir }}/temp"
    state: directory

- name: Download file with custom HTTP headers
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ gnome_extension_dir }}/temp/{{ item.name }}.zip"
  loop: "{{ gnome_extensions_zip }}"

- name: Enable GNOME extensions
  ansible.builtin.shell: |
    gnome-extensions install -f {{ gnome_extension_dir }}/temp/{{ item.name }}.zip
  loop: "{{ gnome_extensions_zip }}"
