- name: Add flatpack repo
  become: true
  ansible.builtin.shell: |
    flatpak remote-add --if-not-exists flathub {{ flatpak_repo }}

- name: Install multiple packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpaks }}"
