- name: services_enabled
  block:
    - name: "SERVICES: Enable services"
      become: true
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop: "{{ services_enabled }}"

- name: services_masked
  block:
    - name: "SERVICES: Mask services"
      become: true
      systemd:
        name: "{{ item }}"
        masked: true
        state: stopped
      loop: "{{ services_masked }}"
