configs_mpv_folder: /home/{{ ansible_env.USER }}/.var/app/io.mpv.Mpv/config

fonts_folder: /home/{{ ansible_env.USER }}/.local/share/fonts

configs_dconf:
  - file: tilix.dconf
    load_to: /com/gexperts/Tilix/
  - file: media-keys.dconf
    load_to: /org/gnome/settings-daemon/plugins/media-keys/
