gnome_extensions:
  - id: 5410
    name: grand-theft-focus@zalckos.github.com
  - id: 4451
    name: logomenu@aryan_k
  - id: 1460
    name: Vitals@CoreCoding.com

gnome_extensions_zip: #name should be uuid from metadata.json
  - url: "https://github.com/harshadgavali/gnome-gesture-improvements/files/14779174/gestureImprovements46%40gestures.zip"
    name: gestureImprovements@gestures

gnome_extension_dir: "/home/{{ ansible_env.USER }}/.local/share/gnome-shell/extensions/"
