# APT
apts:
  - gnome-software-plugin-flatpak
  - gnome-tweaks
  - neofetch
  - bind9-dnsutils
  - mc
  - adb
  - htop
  - bat
  - geoip-bin
  - flatpak
  - tilix
  - zsh
  - nvtop
  - smartmontools
  - yt-dlp
  - sshpass
  #  - terraform
  - wget
  - jq
  - sed
  - unzip
  - timeshift # conf
  - vim
  - tlp
  - tlp-rdw
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

debs:
  - http://repo.yandex.ru/yandex-disk/yandex-disk_latest_amd64.deb

bins_archive: # to /usr/sbin
  - url: https://www.hdsentinel.com/hdslin/hdsentinel-020b-x64.zip
    name: HDSentinel
    new_name: hdsentinel
  - url: https://github.com/ahmetb/kubectx/releases/download/v0.9.5/kubectx_v0.9.5_linux_x86_64.tar.gz
    name: kubectx
  - url: https://github.com/ahmetb/kubectx/releases/download/v0.9.5/kubens_v0.9.5_linux_x86_64.tar.gz
    name: kubens
  - url: https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
    name: speedtest
  - url: https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz
    name: helm

bins: # to /usr/sbin
  - url: https://cdn.dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
    name: kubectl
  - url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    name: argocd

flatpak_repo: "https://dl.flathub.org/repo/flathub.flatpakrepo"

flatpaks:
  - org.gnome.Extensions
  - org.gnome.Evolution
  - org.gnome.Weather
  - org.gnome.Evince
  - org.telegram.desktop
  - com.google.Chrome
  - ru.yandex.Browser
  - org.mozilla.firefox
  - ru.linux_gaming.PortProton
  - io.github.seadve.Kooha
  - org.filezillaproject.Filezilla
  - com.jetbrains.DataGrip
  - io.mpv.Mpv
  - org.gimp.GIMP
  - org.onlyoffice.desktopeditors
  - org.keepassxc.KeePassXC
  - org.getoutline.OutlineManager
  - org.getoutline.OutlineClient
  - dev.k8slens.OpenLens
  - com.valvesoftware.Steam
  - org.qbittorrent.qBittorrent
  - com.slack.Slack
  - org.remmina.Remmina
  - net.cozic.joplin_desktop

snaps_remove:
  - firefox

services_enabled:
  - tlp.service

gnome_extensions:
  - id: 8
    name: places-menu@gnome-shell-extensions.gcampax.github.com
  - id: 517
    name: caffeine@patapon.info
  - id: 4679
    name: burn-my-windows@schneegans.github.com
  - id: 5985
    name: do-not-disturb-while-screen-sharing-or-recording@marcinjahn.com
  - id: 5410
    name: grand-theft-focus@zalckos.github.com
  - id: 4451
    name: logomenu@aryan_k
  - id: 1460
    name: Vitals@CoreCoding.com
  - id: 5470
    name: weatheroclock@CleoMenezesJr.github.io
#  - id: 5278
#    name: pano # no 46 support # https://github.com/oae/gnome-shell-pano/issues/271
#  - id: 2594
#    name: always-indicator # no 46 support # https://github.com/mzur/gnome-shell-always-indicator/issues/21

gnome_extensions_zip: #name should be uuid from metadata.json
  - url: "https://github.com/harshadgavali/gnome-gesture-improvements/files/14779174/gestureImprovements46%40gestures.zip"
    name: gestureImprovements@gestures

gnome_extension_dir: "/home/{{ ansible_env.USER }}/.local/share/gnome-shell/extensions/"

zsh_custom_plugins:
  - url: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    name: zsh-syntax-highlighting

zsh_custom_plugins_dir: "/home/{{ ansible_env.USER }}/.oh-my-zsh/custom/plugins/"

docker_users:
  - "{{ ansible_env.USER }}"

configs_mpv_folder: /home/{{ ansible_env.USER }}/.config

fonts_folder: /home/{{ ansible_env.USER }}/.local/share/fonts

symlinks:
  - source: /usr/bin/gnome-calculator
    destination: /usr/bin/calc
