# APT
apts:
  - gnome-shell-extension-manager
  - gnome-weather
  - gnome-tweaks
  - neofetch
  - mc
  - adb
  - flatpak
  - tilix
#  - zsh - role
  - nvtop
  - smartmontools
  - yt-dlp
  - sshpass
#  - terraform
  - wget
  - jq
  - sed
  - unzip
  - timeshift # conf
  - vim # conf
  - tlp
  - tlp-rdw
  #ansible:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

debs:
  - http://repo.yandex.ru/yandex-disk/yandex-disk_latest_amd64.deb


flatpaks:
  - org.gnome.Evolution
  - org.telegram.desktop
  - com.google.Chrome
  - ru.yandex.Browser
  - org.filezillaproject.Filezilla
  - com.jetbrains.DataGrip
  - io.mpv.Mpv # conf
  - org.gimp.GIMP
  - org.onlyoffice.desktopeditors
  - org.keepassxc.KeePassXC
  - org.getoutline.OutlineManager
  - org.getoutline.OutlineClient
  - dev.k8slens.OpenLens
  - com.valvesoftware.Steam
  - org.qbittorrent.qBittorrent
  - com.slack.Slack
  - org.remmina.Remmina
  - net.cozic.joplin_desktop

services_enabled:
  - tlp.service
  - docker.service
  - docker.socket

gnome_extensions:
  - id: 8
    name: places-status-indicator
  - id: 517
    name: caffeine
  - id: 4679
    name: burn-my-windows
  - id: 5985
    name: do-not-disturb-while-screen-sharing-or-recording
  - id: 5410
    name: grand-theft-focus
  - id: 4451
    name: logo-menu
  - id: 1460
    name: vitals
  - id: 5904
    name: volume-scroller
  - id: 5470
    name: weather-oclock
#  - id: 5278
#    name: pano # no 46 support # https://github.com/oae/gnome-shell-pano/issues/271
#  - id: 2594
#    name: always-indicator # no 46 support # https://github.com/mzur/gnome-shell-always-indicator/issues/21

gnome_extensions_zip: #name should be uuid from metadata.json
  - url: "https://github.com/harshadgavali/gnome-gesture-improvements/files/14779174/gestureImprovements46%40gestures.zip"
    name: gestureImprovements@gestures

gnome_extension_dir: "~/.local/share/gnome-shell/extensions/"
