- name: All servers setup
  hosts: all
  become: yes
  connection: local

  roles:
    - role: ansible-role-docker
    - role: ansible-role-zsh
    - role: ansible-role-customize-gnome

  tasks:
    - include_vars:
        file: includes/main-vars.yml
    - include_tasks: tasks/apt.yml

#    - include_tasks: tasks/package-dependencies.yaml
#    - include_tasks: tasks/package-install.yaml
#    - include_tasks: tasks/git-setup.yaml
#    - include_tasks: tasks/dotfiles.yaml
#    - include_tasks: tasks/security.yaml
#    - include_tasks: tasks/service-enable.yaml
#    - include_tasks: tasks/docker.yaml
