- name: All servers setup
  hosts: all
  become_method: sudo
  connection: local

  vars_files:
    - includes/main-vars.yml

  pre_tasks:
    - include_tasks: tasks/apt.yml
    - include_tasks: tasks/flatpak.yml
    - include_tasks: tasks/extensions.yml

  roles:
    - role: ansible-role-docker
    - role: ansible-role-zsh

  post_tasks:
    - include_tasks: tasks/services-enable.yml
